using System.Text;

namespace Novolis.Game.Packaging.Inno;

/// <summary>Builds a per-user Inno Setup script from publish output metadata.</summary>
public sealed class InnoScriptGenerator
{
    /// <summary>Application display name in the installer.</summary>
    public required string AppName { get; init; }

    /// <summary>Semantic version written to the script.</summary>
    public required string AppVersion { get; init; }

    /// <summary>Folder containing published game binaries.</summary>
    public required string PublishDir { get; init; }

    /// <summary>Executable name launched by shortcuts.</summary>
    public required string AppExeName { get; init; }

    /// <summary>Directory where Inno writes the compiled installer.</summary>
    public required string OutputDir { get; init; }

    /// <summary>Installer application identifier used for upgrades.</summary>
    public string AppId { get; init; } = "Novolis.Game";

    /// <summary>Windows Start Menu group name.</summary>
    public string DefaultGroupName { get; init; } = "Novolis";

    /// <summary>Output setup executable base name (without extension).</summary>
    public string OutputBaseFilename { get; init; } = "NovolisGameSetup";

    /// <summary>Per-user installation directory suffix under LocalAppData\Programs.</summary>
    public string InstallDirName { get; init; } = @"Novolis\Game";

    /// <summary>Publisher display name (Novolis is the public brand).</summary>
    public string AppPublisher { get; init; } = "Novolis";

    /// <summary>Canonical user-facing URL — the GitHub organization.</summary>
    public string AppPublisherUrl { get; init; } = "https://github.com/Novolis-Platform";

    /// <summary>Support URL (issues, help desk).</summary>
    public string? AppSupportUrl { get; init; }

    /// <summary>Update/download URL for new releases.</summary>
    public string? AppUpdatesUrl { get; init; }

    /// <summary>Copyright string embedded in version info.</summary>
    public string AppCopyright { get; init; } = "Copyright (c) Novolis";

    /// <summary>Company field in the setup EXE version resource.</summary>
    public string VersionInfoCompany { get; init; } = "Novolis";

    /// <summary>Optional setup wizard / EXE icon path.</summary>
    public string? SetupIconFile { get; init; }

    /// <summary>Optional MIT license file shown in the wizard.</summary>
    public string? LicenseFile { get; init; }

    /// <summary>Emits an Inno Setup script as text.</summary>
    public string Generate()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(AppName);
        ArgumentException.ThrowIfNullOrWhiteSpace(AppVersion);
        ArgumentException.ThrowIfNullOrWhiteSpace(PublishDir);
        ArgumentException.ThrowIfNullOrWhiteSpace(AppExeName);
        ArgumentException.ThrowIfNullOrWhiteSpace(OutputDir);
        ArgumentException.ThrowIfNullOrWhiteSpace(AppId);
        ArgumentException.ThrowIfNullOrWhiteSpace(InstallDirName);

        var publish = PublishDir.TrimEnd('\\', '/');
        var sb = new StringBuilder();
        sb.AppendLine("; Generated by Novolis.Game.Packaging.Inno");
        sb.AppendLine("; Per-user install (no admin). Brand: Novolis. Canonical URL: https://github.com/Novolis-Platform");
        sb.AppendLine("[Setup]");
        sb.AppendLine($"AppId={AppId}");
        sb.AppendLine($"AppName={AppName}");
        sb.AppendLine($"AppVersion={AppVersion}");
        sb.AppendLine($"AppPublisher={AppPublisher}");
        sb.AppendLine($"AppPublisherURL={AppPublisherUrl}");
        if (!string.IsNullOrWhiteSpace(AppSupportUrl))
            sb.AppendLine($"AppSupportURL={AppSupportUrl}");
        if (!string.IsNullOrWhiteSpace(AppUpdatesUrl))
            sb.AppendLine($"AppUpdatesURL={AppUpdatesUrl}");
        sb.AppendLine($"AppCopyright={AppCopyright}");
        sb.AppendLine($"VersionInfoVersion={AppVersion}");
        sb.AppendLine($"VersionInfoCompany={VersionInfoCompany}");
        sb.AppendLine($"VersionInfoProduct={AppName}");
        sb.AppendLine($"VersionInfoCopyright={AppCopyright}");
        sb.AppendLine($"VersionInfoDescription={AppName} - Novolis");
        sb.AppendLine($"DefaultDirName={{localappdata}}\\Programs\\{InstallDirName}");
        sb.AppendLine($"DefaultGroupName={DefaultGroupName}");
        sb.AppendLine($"OutputBaseFilename={OutputBaseFilename}");
        sb.AppendLine($"OutputDir={OutputDir}");
        sb.AppendLine("PrivilegesRequired=lowest");
        sb.AppendLine("UsePreviousAppDir=yes");
        sb.AppendLine("DisableDirPage=auto");
        sb.AppendLine("CloseApplications=yes");
        sb.AppendLine($"CloseApplicationsFilter={AppExeName}");
        sb.AppendLine("RestartApplications=yes");
        sb.AppendLine("DisableProgramGroupPage=yes");
        sb.AppendLine("WizardStyle=modern");
        sb.AppendLine("ArchitecturesAllowed=x64compatible");
        sb.AppendLine("ArchitecturesInstallIn64BitMode=x64");
        sb.AppendLine("Compression=lzma2");
        sb.AppendLine("SolidCompression=yes");
        sb.AppendLine($"UninstallDisplayIcon={{app}}\\{AppExeName}");
        if (!string.IsNullOrWhiteSpace(SetupIconFile))
            sb.AppendLine($"SetupIconFile={SetupIconFile}");
        if (!string.IsNullOrWhiteSpace(LicenseFile))
            sb.AppendLine($"LicenseFile={LicenseFile}");
        sb.AppendLine();
        sb.AppendLine("[Tasks]");
        sb.AppendLine("Name: \"desktopicon\"; Description: \"Create a &desktop icon\"; GroupDescription: \"Additional icons:\"; Flags: unchecked");
        sb.AppendLine();
        sb.AppendLine("[Files]");
        sb.AppendLine($"Source: \"{publish}\\*\"; DestDir: \"{{app}}\"; Flags: ignoreversion recursesubdirs createallsubdirs");
        sb.AppendLine();
        sb.AppendLine("[Icons]");
        sb.AppendLine($"Name: \"{{autoprograms}}\\{DefaultGroupName}\"; Filename: \"{{app}}\\{AppExeName}\"");
        sb.AppendLine($"Name: \"{{autodesktop}}\\{DefaultGroupName}\"; Filename: \"{{app}}\\{AppExeName}\"; Tasks: desktopicon");
        sb.AppendLine();
        sb.AppendLine("[Run]");
        sb.AppendLine($"Filename: \"{{app}}\\{AppExeName}\"; Description: \"Launch {AppName}\"; Flags: nowait postinstall skipifsilent");
        return sb.ToString();
    }
}
