using System.Text;

namespace Novolis.Game.Packaging.Inno;

/// <summary>Builds a minimal Inno Setup script from publish output metadata.</summary>
public sealed class InnoScriptGenerator
{
    /// <summary>Application display name in the installer.</summary>
    public required string AppName { get; init; }

    /// <summary>Semantic version written to the script.</summary>
    public required string AppVersion { get; init; }

    /// <summary>Folder containing published game binaries.</summary>
    public required string PublishDir { get; init; }

    /// <summary>Output setup executable base name (without extension).</summary>
    public string OutputBaseFilename { get; init; } = "setup";

    /// <summary>Emits an Inno Setup script as text.</summary>
    public string Generate()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(AppName);
        ArgumentException.ThrowIfNullOrWhiteSpace(AppVersion);
        ArgumentException.ThrowIfNullOrWhiteSpace(PublishDir);

        var publish = PublishDir.TrimEnd('\\', '/');
        var sb = new StringBuilder();
        sb.AppendLine("; Generated by Novolis.Game.Packaging.Inno");
        sb.AppendLine("[Setup]");
        sb.AppendLine($"AppName={AppName}");
        sb.AppendLine($"AppVersion={AppVersion}");
        sb.AppendLine($"DefaultDirName={{autopf}}\\{AppName}");
        sb.AppendLine($"OutputBaseFilename={OutputBaseFilename}");
        sb.AppendLine();
        sb.AppendLine("[Files]");
        sb.AppendLine($"Source: \"{publish}\\*\"; DestDir: \"{{app}}\"; Flags: ignoreversion recursesubdirs");
        return sb.ToString();
    }
}
